<?php
// $Id$

/**
 * @file
 * The password policy password tab module adds a separate tab to change password.
 */

//////////////////////////////////////////////////////////////////////////////
// Core API hooks

/**
 * Implementation of hook_menu().
 */
function password_policy_password_tab_menu() {
  $items['user/%user/password'] = array(
    'title' => 'Passowrd',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('password_policy_password_tab', 1),
    'access callback' => 'user_edit_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'file' => 'password_policy_password_tab.pages.inc',
  );
  return $items;
}

/**
 * Implementation of hook_form_alter().
 */
function password_policy_password_tab_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case "user_profile_form":
      unset($form['account']['pass']);
      break;
  }
}

